rm: add a test and fix a test typo.
* tests/rm/warnings-no-symlinks: Fix a typo.  Add a test.

diff --git a/tests/rm/warnings-no-symlinks b/tests/rm/warnings-no-symlinks
--- a/tests/rm/warnings-no-symlinks
+++ b/tests/rm/warnings-no-symlinks
@@ -26,7 +26,7 @@ fi
 . $srcdir/test-lib.sh
 
 mkdir -p $test.home/.rmfd dir-1 || framework_failure
-touch file-1 file-2 dir-1/file1-1 || framework_failure
+touch file-1 file-2 file-3 dir-1/file1-1 || framework_failure
 echo y > $test.Iy || framework_failure
 echo n > $test.In || framework_failure
 rm -f out err || framework_failure
@@ -76,7 +76,13 @@ echo 'no warn.list file' >> err || fail=1
 rm $warnlist || fail=1
 rm -w file-2 >> out 2>> err || fail=1
 echo . >> err || fail=1
-test -f dir-2 && fail=1
+test -f file-2 && fail=1
+
+echo 'a non-existent file in warn.list' >> err || fail=1
+echo '/poop/plop/plunk' > $warnlist || fail=1
+rm -w file-3 >> out 2>> err || fail=1
+echo . >> err || fail=1
+test -f file-3 && fail=1
 
 cat <<EOF > expout || fail=1
 EOF
@@ -95,6 +101,8 @@ rm: WARNING: you are about to remove \`$(pwd)/dir-1/file1-1'; continue? .
 file under directory in warn.list, answer yes
 rm: WARNING: you are about to remove \`$(pwd)/dir-1/file1-1'; continue? .
 no warn.list file
+.
+a non-existent file in warn.list
 .
 EOF
 
